name: Provision EKS cluster
# run provision vs destroy job by commenting/uncommenting if: false prop

on:
  push:
    branches: [main]
        
permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: "terraform"
jobs:
  provision_resource:
    # if: false
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          # ref: ""
          # path: ""
          sparse-checkout: "terraform"
          sparse-checkout-cone-mode: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
      
      - name: terraform setup
        uses: hashicorp/setup-terraform@v4

      - name: initial terraform
        run: terraform init

      - name: terraform plan
        run: terraform plan -no-color

      - name: terraform apply
        run: terraform apply -auto-approve

      - name: Send EC2 IP to Slack
        run: |
          EKS_CLUSTER_NAME=$(terraform output -raw cluster_name)
          curl -X POST --header "Content-Type: application/json" -d "{\"text\": \"EKS cluster $EKS_CLUSTER_NAME created!\"}" \
          ${{ vars.SLACK_WEBHOOK_URL }}

  destroy_resources:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          # ref: ""
          # path: ""
          sparse-checkout: "terraform"
          sparse-checkout-cone-mode: false

      # - name: Configure AWS Credentials # not needed for tf, just passed those cred as env vars
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
      
      - name: terraform setup
        uses: hashicorp/setup-terraform@v4

      - name: initial terraform
        run: terraform init

      - name: terraform destroy
        run: terraform apply -destroy -auto-approve